### ISSUE TITLE
Sono Bisque Doll wa Koi wo Suru - 04 (Font Issue)

### ISSUE THREAD

**Issue by Arid0914** [GoodJobMedia/gjmbatchscripts#35]
On Windows the usage of "\fnA1 Gothic B Web" doesn't correctly identify the font leaving the sign looking like this:

![Screenshot- GJM  Sono Bisque Doll wa Koi wo Suru (My Dress-Up Darling) - 04  C9CE0207 -T00 00 15 724-F377](https://user-images.githubusercontent.com/62491139/160713726-87bfb371-690b-42c4-a47d-49e1a3dda506.png)

When changing the uses of "\fnA1 Gothic B Web" to "\fnA1 Gothic Web" it looks like this (which is more likely to be the intended look). Tested in mpv and MPC-HC. (It also could just be a missing font but I don't think so).

![GJM  Sono Bisque Doll wa Koi wo Suru (My Dress-Up Darling) - 04  C9CE0207 _001_333](https://user-images.githubusercontent.com/62491139/160714523-d13ffa69-e575-4dcc-b1f7-2bdb1d5de51f.png)

**Comment by joletb** [comment]
Fixed for batch, muxed release was missing the "A1GothicB.ttf" font.
