### ISSUE TITLE
Neverland ep12: Capitalize?

### ISSUE THREAD

**Issue by gu1dry** [GoodJobMedia/gjmbatchscripts#4]
Just thought the 'f' in "find" should be capitalized.

https://github.com/Fyurie/gjmbatchscripts/blob/874110ba425497b5a83106c929bcb7198e136245/Currently%20Airing/Yakusoku%20no%20Neverland/Neverland12-Batch.ass#L182

**Comment by JustaPeriod** [comment]
Taken care of. Thanks for pointing it out.
