### ISSUE TITLE
To Aru Majutsu no Index III Episode 6

### ISSUE THREAD

**Issue by shinigamichan** [GoodJobMedia/gjmbatchscripts#6]
Just testing the waters with a correction for one line rather than dumping a bunch of notes. If you're receptive to corrections, I could send more in one post. https://github.com/Fyurie/gjmbatchscripts/pull/5

JPN CC: 似合わねえな メルヘン野郎
Original: Those don't suit you at all, you nut job.
Correction: you nut job -> fairy tale boy
Note: Appears to be a mishearing of  メンヘラ (nutjob) for メルヘン (fairytale). Accelerator is making fun of the appearance of Kakine's wings.
LN volume 15 raw:
「似合わねェな、メルヘン野郎」
「心配するな。白覚はある」

**Comment by Fyurie** [comment]
We're always welcome to feedback.

We'd probably not lift a PR as-is and might cherry-pick/change phrasing choices, but any oral feedback, as it were, will be looked into and discussed when the time comes around that we work on said episode(s).

**Comment by shinigamichan** [comment]
Is this a good place to post feedback or should I do it somewhere else? I couldn't find anything clear on the website. I could do a gist with notes or something.

**Comment by Fyurie** [comment]
A Gist works. As long as it's not set to expire or such, I'll put it on GJM's internal tools to refer to.

**Comment by shinigamichan** [comment]
Sure, here are the notes. Unfortunately the web interface doesn't wrap the text, but it's all there. Ask me if you have any questions. Closing this issue and the pull request.

https://gist.github.com/shinigamichan/1b58df776d8f926975765338f62c6fea

Edit: Added markdown so it's actually readable.
